# FlatBedrock Configuration file for version 1.00
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/FlatBedrock

#==================#
#   Basic Config   #
#==================#
# Default radius to check at a time (default: 8)
Radius: 8

# Maximum radius to check at a time (default: 250)
# The server may freeze when you increase this value.
# It's RECOMMENDED that you do NOT to a value greater than default.
MaxRadius: 250
