##  Plugin Information  ##
name: FlatBedrock
version: 1.1
main: syam.FlatBedrock.FlatBedrock
description: FlatBedrock
website: http://sakura-server.net/
softdepend: [Vault]
##  Original Author     ##
author: syam
commands:
    flatbedrock:
      usage: /flatbedrock - to see the help
      aliases: [flatbed, fbr]
      description: To see the FlatBedrock help.
permissions:
    flatbedrock.reload:
        default: op
        description: Allow reload configuration!
    flatbedrock.use:
        default: op
        description: Flattens bedrock in specified radius
    flatbedrock.auto:
        default: false
        description: Auto bedrock flat on player move!
    flatbedrock.pay:
        default: op
        description: Flattens bedrock and needs pay cost